# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a1b83720b9efe9a8a448b561df3c0b0276c0f2c6accfd95e71f6e6f50e645cb284167fe7227204fd6f699557f4e77bc64a8e07857274aa6ae6263e355dd3538

test:
  secret_key_base: 36ec5697dba089175f2020efdfa9610ae26a2854c3f40b089befade49339a3df333c2dfa982baaefa0c0f05e6ef8d9533dccf2bb87d44796f2bf9aff4633f902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
